const tourneydata = [
  {
    id: 1,
    game: '2k23',
    prize: '$20',
    date: 'Jun 16, 2022',
    country: 'NA + EU',
    difficulty: 'Novice',
    enrolled: '0',
    entry_credits: 5,
    tourney_type: 'Community Tournament',
    type: '1v1 blacktop',
    img: '/images/2k23/2k23g.webp',
    team_size: '1 v 1',
    max_teams: 32,
    platform: 'console',
    place: {
      first_place: '$100',
      second_place: '$50',
      third_place: '$25',
    },
    registration: 'Open',
    start_time: '2:00pm',
  },
  {
    id: 2,
    game: 'Fortnite',
    prize: '$50',
    date: 'Aug 20, 2022',
    country: 'Global',
    difficulty: 'Intermediate',
    enrolled: '0',
    entry_credits: 10,
    tourney_type: 'Solo Tournament',
    type: 'Battle Royale',
    img: '/images/fortnite/fortnite.webp',
    team_size: '1',
    max_teams: 100,
    platform: 'PC',
    place: {
      first_place: '$500',
      second_place: '$250',
      third_place: '$100',
    },
    registration: 'Closed',
    start_time: '6:00pm',
  },
  {
    id: 3,
    game: 'League of Legends',
    prize: '$100',
    date: 'Sep 10, 2022',
    country: 'NA',
    difficulty: 'Expert',
    enrolled: '0',
    entry_credits: 20,
    tourney_type: '5v5 Team Tournament',
    type: 'MOBA',
    img: '/images/lol/lol.webp',
    team_size: '5',
    max_teams: 16,
    platform: 'PC',
    place: {
      first_place: '$1000',
      second_place: '$500',
      third_place: '$250',
    },
    registration: 'Open',
    start_time: '7:00pm',
  },
  {
    id: 4,
    game: 'Valorant',
    prize: '$75',
    date: 'Oct 5, 2022',
    country: 'EU',
    difficulty: 'Intermediate',
    enrolled: '0',
    entry_credits: 15,
    tourney_type: 'Duo Tournament',
    type: 'Tactical Shooter',
    img: '/images/valorant/valorant.webp',
    team_size: '2',
    max_teams: 64,
    platform: 'PC',
    place: {
      first_place: '$750',
      second_place: '$400',
      third_place: '$200',
    },
    registration: 'Open',
    start_time: '8:00pm',
  },
  {
    id: 5,
    game: 'Apex Legends',
    prize: '$60',
    date: 'Nov 15, 2022',
    country: 'Global',
    difficulty: 'Intermediate',
    enrolled: '0',
    entry_credits: 12,
    tourney_type: 'Squad Tournament',
    type: 'Battle Royale',
    img: '/images/apex/apex.webp',
    team_size: '3',
    max_teams: 50,
    platform: 'Console',
    place: {
      first_place: '$600',
      second_place: '$300',
      third_place: '$150',
    },
    registration: 'Open',
    start_time: '5:00pm',
  },
  {
    id: 6,
    game: 'Call of Duty: Warzone',
    prize: '$80',
    date: 'Dec 1, 2022',
    country: 'NA',
    difficulty: 'Expert',
    enrolled: '0',
    entry_credits: 16,
    tourney_type: 'Quad Tournament',
    type: 'Battle Royale',
    img: '/images/warzone/warzone.webp',
    team_size: '4',
    max_teams: 40,
    platform: 'Console',
    place: {
      first_place: '$800',
      second_place: '$450',
      third_place: '$200',
    },
    registration: 'Open',
    start_time: '4:00pm',
  },
  {
    id: 7,
    game: 'Call of Duty: Warzone',
    prize: '$80',
    date: 'Dec 1, 2022',
    country: 'NA',
    difficulty: 'Expert',
    enrolled: '0',
    entry_credits: 16,
    tourney_type: 'Quad Tournament',
    type: 'Battle Royale',
    img: '/images/warzone/warzone.webp',
    team_size: '4',
    max_teams: 40,
    platform: 'Console',
    place: {
      first_place: '$800',
      second_place: '$450',
      third_place: '$200',
    },
    registration: 'Open',
    start_time: '4:00pm',
  },
  {
    id: 8,
    game: 'Call of Duty: Warzone',
    prize: '$80',
    date: 'Dec 1, 2022',
    country: 'NA',
    difficulty: 'Expert',
    enrolled: '0',
    entry_credits: 16,
    tourney_type: 'Quad Tournament',
    type: 'Battle Royale',
    img: '/images/warzone/warzone.webp',
    team_size: '4',
    max_teams: 40,
    platform: 'Console',
    place: {
      first_place: '$800',
      second_place: '$450',
      third_place: '$200',
    },
    registration: 'Open',
    start_time: '4:00pm',
  },
  {
    id: 9,
    game: 'Call of Duty: Warzone',
    prize: '$80',
    date: 'Dec 1, 2022',
    country: 'NA',
    difficulty: 'Expert',
    enrolled: '0',
    entry_credits: 16,
    tourney_type: 'Quad Tournament',
    type: 'Battle Royale',
    img: '/images/warzone/warzone.webp',
    team_size: '4',
    max_teams: 40,
    platform: 'Console',
    place: {
      first_place: '$800',
      second_place: '$450',
      third_place: '$200',
    },
    registration: 'Open',
    start_time: '4:00pm',
  },
  {
    id: 10,
    game: 'Call of Duty: Warzone',
    prize: '$80',
    date: 'Dec 1, 2022',
    country: 'NA',
    difficulty: 'Expert',
    enrolled: '0',
    entry_credits: 16,
    tourney_type: 'Quad Tournament',
    type: 'Battle Royale',
    img: '/images/warzone/warzone.webp',
    team_size: '4',
    max_teams: 40,
    platform: 'Console',
    place: {
      first_place: '$800',
      second_place: '$450',
      third_place: '$200',
    },
    registration: 'Open',
    start_time: '4:00pm',
  },
  {
    id: 11,
    game: 'Call of Duty: Warzone',
    prize: '$80',
    date: 'Dec 1, 2022',
    country: 'NA',
    difficulty: 'Expert',
    enrolled: '0',
    entry_credits: 16,
    tourney_type: 'Quad Tournament',
    type: 'Battle Royale',
    img: '/images/warzone/warzone.webp',
    team_size: '4',
    max_teams: 40,
    platform: 'Console',
    place: {
      first_place: '$800',
      second_place: '$450',
      third_place: '$200',
    },
    registration: 'Open',
    start_time: '4:00pm',
  },
  {
    id: 12,
    game: 'Call of Duty: Warzone',
    prize: '$80',
    date: 'Dec 1, 2022',
    country: 'NA',
    difficulty: 'Expert',
    enrolled: '0',
    entry_credits: 16,
    tourney_type: 'Quad Tournament',
    type: 'Battle Royale',
    img: '/images/warzone/warzone.webp',
    team_size: '4',
    max_teams: 40,
    platform: 'Console',
    place: {
      first_place: '$800',
      second_place: '$450',
      third_place: '$200',
    },
    registration: 'Open',
    start_time: '4:00pm',
  },
]

export default tourneydata
